"""
Nurse Mentor AI - Report generator.

Generates:
    - Plain text reports (fallback)
    - PDF reports with clinic branding (Dr. Rahila Ali)
    - Preparer signature (Fahad Ali) in Great Vibes font

Pure backend - no UI, no Kivy dependency.
"""

import os
from datetime import datetime

from fpdf import FPDF

import database as db


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPORTS_DIR = os.path.join(BASE_DIR, "reports")
FONT_PATH = os.path.join(BASE_DIR, "fonts", "GreatVibes-Regular.ttf")

# Who prepares the report (nurse/operator)
PREPARER_NAME = "Fahad Ali"


# ---------------------------------------------------------------------------
# Clinic branding
# ---------------------------------------------------------------------------
CLINIC_NAME = "Dr. Rahila Ali"
CLINIC_QUALIFICATION = "M.B.B.S, R.M.P"
CLINIC_SPECIALTY = "Family Physician & Sonologist"
CLINIC_CONTACT = "0322-8244709"
CLINIC_TIMING = "11:00 AM to 03:00 PM"

BLUE_HEADER = (26, 82, 153)
BLUE_HEADER_LIGHT = (43, 105, 176)
OFF_WHITE = (247, 245, 240)
TEAL = (0, 138, 122)
ORANGE = (232, 145, 0)
DARK_GREY = (60, 60, 60)
LIGHT_GREY = (200, 200, 200)


def _ensure_reports_dir():
    if not os.path.exists(REPORTS_DIR):
        try:
            os.makedirs(REPORTS_DIR)
        except Exception:
            pass


def _title_for(patient):
    gender = (patient.get("gender") or "").strip().upper()
    if gender == "M":
        return "Mr."
    if gender == "F":
        return "Mrs."
    return ""


# ===========================================================================
class PatientReportPDF(FPDF):
    def __init__(self, patient_name=""):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.patient_name = patient_name
        self.set_auto_page_break(auto=True, margin=20)
        self._font_registered = False

    # ------------------------------------------------------------------
    def _register_signature_font(self):
        if self._font_registered:
            return "GreatVibes"
        if not os.path.exists(FONT_PATH):
            return None
        try:
            self.add_font("GreatVibes", "", FONT_PATH, uni=True)
            self._font_registered = True
            return "GreatVibes"
        except Exception as e:
            print("Font registration failed:", repr(e))
            return None

    # ------------------------------------------------------------------
    def header(self):
        self.set_fill_color(*BLUE_HEADER)
        self.rect(0, 0, 210, 42, style="F")

        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 22)
        self.set_xy(10, 6)
        self.cell(190, 10, CLINIC_NAME, ln=1, align="C")

        self.set_font("Helvetica", "", 11)
        self.set_xy(10, 17)
        self.cell(190, 5, CLINIC_QUALIFICATION, ln=1, align="C")

        self.set_font("Helvetica", "I", 10)
        self.set_xy(10, 22)
        self.cell(190, 5, CLINIC_SPECIALTY, ln=1, align="C")

        self.set_font("Helvetica", "", 9)
        self.set_xy(10, 30)
        self.cell(
            190, 5,
            "Contact: {}    |    Timing: {}".format(CLINIC_CONTACT, CLINIC_TIMING),
            ln=1, align="C",
        )

        self.set_fill_color(*OFF_WHITE)
        self.rect(0, 42, 210, 3, style="F")

        self.set_y(50)

    # ------------------------------------------------------------------
    def footer(self):
        self.set_y(-18)
        self.set_fill_color(*BLUE_HEADER)
        self.rect(0, 279, 210, 18, style="F")

        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "I", 8)
        self.set_xy(10, 283)
        self.cell(
            190, 5,
            "Generated by Nurse Mentor AI  |  Page {}".format(self.page_no()),
            align="C",
        )

    # ------------------------------------------------------------------
    def section_title(self, text, color=None):
        color = color or TEAL
        self.set_text_color(*color)
        self.set_font("Helvetica", "B", 13)
        self.ln(2)
        self.cell(0, 8, text, ln=1)
        y = self.get_y()
        self.set_draw_color(*color)
        self.set_line_width(0.6)
        self.line(10, y, 200, y)
        self.ln(3)

    # ------------------------------------------------------------------
    def info_box(self, patient):
        self.set_fill_color(*OFF_WHITE)
        self.set_draw_color(*LIGHT_GREY)
        self.set_line_width(0.3)

        box_x = 10
        box_y = self.get_y()
        box_w = 190
        box_h = 42

        self.rect(box_x, box_y, box_w, box_h, style="DF")

        title = _title_for(patient)
        full_name = ("{} {}".format(title, patient["name"])).strip()

        self.set_text_color(*DARK_GREY)
        self.set_font("Helvetica", "B", 12)
        self.set_xy(box_x + 4, box_y + 3)
        self.cell(0, 6, full_name, ln=1)

        self.set_font("Helvetica", "", 10)

        self.set_x(box_x + 4)
        age = patient.get("age") or "-"
        gender = (patient.get("gender") or "-").upper()
        phone = patient.get("phone") or "-"
        self.cell(
            90, 6,
            "Age: {}    Gender: {}    Phone: {}".format(age, gender, phone),
            ln=0,
        )
        self.ln(6)

        self.set_x(box_x + 4)
        address = patient.get("address") or "-"
        self.cell(180, 6, "Address: {}".format(address), ln=1)

        self.set_x(box_x + 4)
        registered = (patient.get("created_at") or "-")[:10]
        total_visits = len(db.get_patient_visits(patient["id"]))
        self.cell(
            180, 6,
            "Registered: {}    Total Visits: {}".format(registered, total_visits),
            ln=1,
        )

        self.ln(4)

    # ------------------------------------------------------------------
    def visit_block(self, visit_no, visit_date, procedures, tests):
        self.set_text_color(*BLUE_HEADER_LIGHT)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 7, "Visit #{}  -  {}".format(visit_no, visit_date), ln=1)

        self.set_draw_color(*LIGHT_GREY)
        self.set_line_width(0.3)
        y = self.get_y()
        self.line(10, y, 200, y)
        self.ln(2)

        if not procedures and not tests:
            self.set_text_color(*DARK_GREY)
            self.set_font("Helvetica", "I", 10)
            self.cell(0, 6, "    No procedures or tests recorded.", ln=1)
            self.ln(3)
            return

        if procedures:
            self.set_text_color(*TEAL)
            self.set_font("Helvetica", "B", 10)
            self.cell(0, 6, "    Procedures:", ln=1)
            self.set_text_color(*DARK_GREY)
            self.set_font("Helvetica", "", 10)
            for p in procedures:
                line = "        - {}".format(p["name"])
                if p.get("details"):
                    line += "  ({})".format(p["details"])
                self.cell(0, 5, line, ln=1)
            self.ln(1)

        if tests:
            self.set_text_color(*ORANGE)
            self.set_font("Helvetica", "B", 10)
            self.cell(0, 6, "    Tests:", ln=1)
            self.set_font("Helvetica", "", 10)
            for t in tests:
                if t.get("result"):
                    self.set_text_color(*DARK_GREY)
                    line = "        - {}   Result: {}".format(t["name"], t["result"])
                else:
                    self.set_text_color(*ORANGE)
                    line = "        - {}   Result: Pending".format(t["name"])
                self.cell(0, 5, line, ln=1)
            self.ln(1)

        self.ln(2)

    # ------------------------------------------------------------------
    def signature_block(self):
        """
        Preparer signature block:
            Fahad Ali (Great Vibes) -> line -> "Prepared by" -> Date
        """
        self.ln(12)

        family = self._register_signature_font()
        if family:
            self.set_text_color(*BLUE_HEADER)
            self.set_font(family, "", 28)
            self.cell(0, 14, PREPARER_NAME, ln=1, align="L")
        else:
            self.set_text_color(*BLUE_HEADER)
            self.set_font("Helvetica", "I", 18)
            self.cell(0, 12, PREPARER_NAME, ln=1, align="L")

        # Underline
        y = self.get_y()
        self.set_draw_color(*DARK_GREY)
        self.set_line_width(0.4)
        self.line(10, y, 85, y)
        self.ln(1)

        # "Prepared by" label
        self.set_text_color(*DARK_GREY)
        self.set_font("Helvetica", "", 10)
        self.cell(0, 5, "Prepared by", ln=1, align="L")

        self.ln(6)

        # Date
        self.cell(0, 6, "Date: {}".format(
            datetime.now().strftime("%Y-%m-%d")
        ), ln=1)


def build_patient_pdf(patient_id):
    patient = db.get_patient(patient_id)
    if not patient:
        return None

    _ensure_reports_dir()

    pdf = PatientReportPDF(patient_name=patient["name"])
    pdf.add_page()

    pdf.set_text_color(*DARK_GREY)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "PATIENT REPORT", ln=1, align="C")
    pdf.ln(2)

    pdf.info_box(patient)
    pdf.section_title("VISIT HISTORY")

    visits = db.get_patient_visits(patient_id)
    if not visits:
        pdf.set_text_color(*DARK_GREY)
        pdf.set_font("Helvetica", "I", 11)
        pdf.cell(0, 8, "No visits recorded.", ln=1)
    else:
        total = len(visits)
        for i, visit in enumerate(visits):
            visit_no = total - i
            procedures = db.get_visit_procedures(visit["id"])
            tests = db.get_visit_tests(visit["id"])
            pdf.visit_block(visit_no, visit["visit_date"], procedures, tests)

    # Preparer signature
    pdf.signature_block()

    safe_name = "".join(c if c.isalnum() else "_" for c in patient["name"])
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = "patient_{}_{}_{}.pdf".format(patient["id"], safe_name, date_str)
    filepath = os.path.join(REPORTS_DIR, filename)

    try:
        pdf.output(filepath)
        return filepath
    except Exception as e:
        print("PDF generation failed:", repr(e))
        return None


# ===========================================================================
# TEXT REPORT (unchanged)
# ===========================================================================
def _title_for_text(patient):
    t = _title_for(patient)
    name = patient["name"]
    return ("{} {}".format(t, name)).strip()


def build_patient_report_text(patient_id):
    patient = db.get_patient(patient_id)
    if not patient:
        return "Patient not found."

    visits = db.get_patient_visits(patient_id)

    lines = []
    lines.append("=" * 60)
    lines.append(CLINIC_NAME.center(60))
    lines.append(CLINIC_QUALIFICATION.center(60))
    lines.append(CLINIC_SPECIALTY.center(60))
    lines.append("Contact: {}   Timing: {}".format(CLINIC_CONTACT, CLINIC_TIMING).center(60))
    lines.append("=" * 60)
    lines.append("")
    lines.append("PATIENT REPORT".center(60))
    lines.append("")
    lines.append("-" * 60)
    lines.append("Patient ID   : {}".format(patient["id"]))
    lines.append("Name         : {}".format(_title_for_text(patient)))
    lines.append("Age          : {}".format(patient.get("age") or "-"))
    lines.append("Gender       : {}".format((patient.get("gender") or "-").upper()))
    lines.append("Phone        : {}".format(patient.get("phone") or "-"))
    lines.append("Address      : {}".format(patient.get("address") or "-"))
    lines.append("Registered   : {}".format(patient.get("created_at") or "-"))
    lines.append("Total Visits : {}".format(len(visits)))
    lines.append("")
    lines.append("Report generated: {}".format(
        datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ))
    lines.append("-" * 60)
    lines.append("VISIT HISTORY")
    lines.append("-" * 60)
    lines.append("")

    if not visits:
        lines.append("No visits recorded.")
    else:
        total = len(visits)
        for i, visit in enumerate(visits):
            visit_no = total - i
            lines.append("Visit #{}  -  {}".format(visit_no, visit["visit_date"]))
            lines.append("")
            procs = db.get_visit_procedures(visit["id"])
            tests = db.get_visit_tests(visit["id"])
            if not procs and not tests:
                lines.append("    (No procedures or tests)")
                lines.append("")
                continue
            if procs:
                lines.append("    Procedures:")
                for p in procs:
                    text = "      - {}".format(p["name"])
                    if p.get("details"):
                        text += "  ({})".format(p["details"])
                    lines.append(text)
                lines.append("")
            if tests:
                lines.append("    Tests:")
                for t in tests:
                    text = "      - {}".format(t["name"])
                    if t.get("result"):
                        text += "  Result: {}".format(t["result"])
                    else:
                        text += "  Result: Pending"
                    lines.append(text)
                lines.append("")

    lines.append("=" * 60)
    lines.append("Prepared by: {}".format(PREPARER_NAME))
    lines.append("Date: {}".format(datetime.now().strftime("%Y-%m-%d")))
    lines.append("=" * 60)

    return "\n".join(lines)


def save_patient_report_text(patient_id):
    patient = db.get_patient(patient_id)
    if not patient:
        return None

    _ensure_reports_dir()
    safe_name = "".join(c if c.isalnum() else "_" for c in patient["name"])
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = "patient_{}_{}_{}.txt".format(patient["id"], safe_name, date_str)
    filepath = os.path.join(REPORTS_DIR, filename)

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(build_patient_report_text(patient_id))
        return filepath
    except Exception:
        return None